name: Publish Release

on:
  workflow_call:
    inputs:
      projects:
        description: 'List of project names to build and publish (formatted as JSON array, e.g. `["ProjectA", "ProjectB"]`)'
        required: true
        type: string
      release-upload-url:
        description: 'Release upload URL for the GitHub release where the package will be uploaded'
        required: true
        type: string
    secrets:
      NUGET_API_KEY:
        required: true

jobs:
  setup:
    name: Validate input
    runs-on: ubuntu-latest

    steps:
    - name: Validate projects input
      run: |
        echo '${{ inputs.projects }}' | jq . > /dev/null || (echo "Error: 'projects' input is not valid JSON." && exit 1)

  build-and-publish:
    name: Publish ${{ matrix.project }} Release
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        project: ${{ fromJson(inputs.projects) }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Restore dependencies
      run: dotnet restore

    - name: Find project file
      id: get-project
      run: |
        project=$(find ${{ matrix.project }} -type f -name "*.csproj" | head -n 1)
        echo "path=$project" >> "$GITHUB_OUTPUT"

    - name: Get project version
      uses: bbonkr/get-version-action@v1
      id: get-version
      with:
        project: ${{ steps.get-project.outputs.path }}
        show_log_message: true

    - name: Build NuGet Package
      run: |
        dotnet build \
          --configuration Release \
          --output ${{ matrix.project }}/nupkg \
          ${{ steps.get-project.outputs.path }}

    - name: Find package
      id: get-package
      run: |
        package=$(find ${{ matrix.project }}/nupkg -type f -name "*.nupkg")
        echo "path=$package" >> "$GITHUB_OUTPUT"
        echo "name=$(basename $package)" >> "$GITHUB_OUTPUT"

    - name: Publish to Nuget
      id: nuget-push
      run: |
        set -e
        dotnet nuget push "${{ steps.get-package.outputs.path }}" \
          --api-key "${{ secrets.NUGET_API_KEY }}" \
          --source "https://api.nuget.org/v3/index.json" --skip-duplicate || echo "NuGet push exited with code $?"

    - name: Check for duplicate package
      if: failure() && steps.nuget-push.outcome == 'failure'
      run: |
        echo "The package may have been skipped because it is a duplicate (already exists on NuGet)."

    - name: Publish asset to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ inputs.release-upload-url }}
        asset_path: ${{ steps.get-package.outputs.path }}
        asset_name: ${{ steps.get-package.outputs.name }}
        asset_content_type: application/x-nupkg